services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data