services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: react-app
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
    container_name: flask-api
    expose:
      - 5000
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      # - frontend
      - backend